apiVersion: v1
kind: Secret
metadata:
  name: misc-service-secrets
  namespace: production
type: Opaque
data:
  ENCRYPT_PASSWORD: bXlfMzJfY2hhcnNfZW5jcnlwdGlvbl9rZXlfMTIzNDU=
  TURNCREDENTIALS_SECRET: dHVybnF3b2VpcXdlNzFicXdpZWpxd2lvZWpvcQ==
  SERVICE_TOKEN_SECRET: bXlqd3RzM2NyM3Q=