apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: production
  labels:
    app: reservation-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: reservation-service
  type: NodePort
