apiVersion: v1
kind: Service
metadata:
  name: misc-service
  namespace: production
  labels:
    app: misc-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: misc-service
  type: NodePort
